build: false
image: Visual Studio 2015

platform:
  - x64
  - x86

clone_depth: 50

install:
  - git submodule update --init --recursive  # retrieve fast_rgf
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%  # Delete sh.exe from PATH (mingw32-make fix)
  - ps: >-
      switch($env:PYTHON_VERSION) {
          "2.7" {$env:MINICONDA = """C:\Miniconda"""}
          "3.4" {$env:MINICONDA = """C:\Miniconda34"""}
          "3.5" {$env:MINICONDA = """C:\Miniconda35"""}
          "3.6" {$env:MINICONDA = """C:\Miniconda36"""}
          default {$env:MINICONDA = """C:\Miniconda36"""}
      }
  - ps: >-
      if($env:PLATFORM -eq "x64") {
          $env:MINICONDA += "-x64";
          $env:PATH += ";C:\Qt\Tools\mingw530_32\bin"
      }
      else {$env:PATH += ";C:\Qt\Tools\mingw530_32\bin"}

test_script:
  - cd include/fast_rgf/build
  - cmake .. -G "MinGW Makefiles"
  - mingw32-make
  - mingw32-make install
  - ps: >-
      $test = Get-Content C:\projects\rgf-python\include\fast_rgf\examples\ex2\inputs\housing.train;
      $output = $test[0..6];
      Set-Content -Path C:\projects\rgf-python\include\fast_rgf\examples\ex2\inputs\housing.train -Value $output;
  - type C:\projects\rgf-python\include\fast_rgf\examples\ex2\inputs\housing.train
  - cd ../bin
  - forest_train.exe trn.x-file="../examples/ex2/inputs/housing.train" trn.x-file_format="y.x" trn.target=REAL model.save="../examples/ex2/outputs/model-rgf"
