sudo: false

# Travis CI does not currently support Python on Mac OS X
language: generic

os:
  - linux
  - osx

git:
  submodules: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install gcc;
      brew link --overwrite gcc;
      export CXX=g++-7 && export CC=gcc-7;
    else
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get update;
      sudo apt-get install g++-5;
      export CXX=g++-5 && export CC=gcc-5;
    fi

install:
  - cd include/fast_rgf/build
  - cmake ..
  - make
  - make install
  - cd ../examples/ex2/inputs
  - head -5 housing.train > tmpfile
  - cat tmpfile > housing.train
  - cat housing.train
  - cd ../

script:
  - ./run.sh
